# AIGC视频质量筛选配置文件（仅使用YOLO）

# 质量阈值设置
quality_thresholds:
  # 人体姿态指标
  pose_confidence_threshold: 0.5  # 姿态检测置信度
  overall_pass_score: 0.6        # 总体通过分数（0-1）

# 视频处理参数
video_processing:
  sample_fps: 10                  # 采样帧率（从视频中提取帧的频率）
  max_frames: 30                  # 最大处理帧数（约3秒）
  resize_height: 720              # 处理时的视频高度
  resize_width: 1280              # 处理时的视频宽度

# 输出设置
output:
  save_report: true               # 保存详细报告
  output_dir: "./results"         # 输出目录