# AIGC视频质量筛选配置文件 - 带缓存控制
quality_thresholds:
  blur_threshold: 100.0
  noise_threshold: 30.0
  contrast_threshold: 30.0
  overall_pass_score: 0.6
  temporal_consistency_threshold: 0.7

detection_modules:
  enable_blur_detection: true
  enable_noise_detection: true
  enable_pose_detection: true
  enable_temporal_consistency: true

video_processing:
  sample_fps: 10
  max_frames: 30
  resize_height: 720
  resize_width: 1280

# MediaPipe缓存配置
mediapipe_cache_dir: "./mediapipe_cache"  # 自定义缓存目录

output:
  save_report: true
  save_visualization: false
  output_dir: "./results"
